sounds:
  open:
    name: block_shulker_box_open
    pitch: 1.3
    volume: .7
  close:
    name: block_shulker_box_close
    pitch: 1.3
    volume: .7
  pickUp:
    name: item_armor_equip_chain
    pitch: 2.0
    volume: .7

InvClickOpen:
  enabled: true
  click: SHIFT_RIGHT

AirClickOpen:
  enabled: false
  needShift: true

PickUpItems: # may not work on some versions, need plugin restart to be changed
  enabled: true

# my discord -> {goudzza]