sounds:
  open:
    name: block_shulker_box_open
    pitch: 1.3
    volume: .7
  close:
    name: block_shulker_box_close
    pitch: 1.3
    volume: .7

InvClickOpen:
  enabled: true
  click: SHIFT_RIGHT

AirClickOpen:
  enabled: false
  needShift: true

# my discord -> {goudzza]